inherit_from: .rubocop_todo.yml

inherit_gem:
  prettier: rubocop.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'

Rails/I18nLocaleTexts:
  Enabled: false
