version: "3.9"

x-base: &base
  image: gateway
  environment:
    DATABASE_URL: postgresql://postgres:hunter2@postgres:5432/gateway
    REDIS_URL: redis://redis:6379/12
    NODE_ENV: development
    RAILS_ENV: development
    WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
  depends_on:
    - postgres
  volumes:
    - .:/usr/src/app
    - log:/usr/src/app/log
    - tmp:/usr/src/app/tmp
    - storage:/usr/src/app/storage
    - node_modules:/usr/src/app/node_modules
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: hunter2
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
  rails:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    entrypoint: bin/entrypoint.sh
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    <<: *base
  webpack:
    command: ./bin/webpack-dev-server
    ports:
      - "3035:3035"
    <<: *base
volumes:
  log:
  node_modules:
  pg-data:
  storage:
  tmp:
