version: 2.1
orbs:
  ruby: circleci/ruby@1.1.3

jobs:
  build:
    docker:
      - image: circleci/ruby:3.0.1
        environment:
          DATABASE_URL: postgres://ubuntu@localhost:5432/gateway
          APP_ENV: test
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_DB: gateway
          POSTGRES_HOST_AUTH_METHOD: trust
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - ruby/rspec-test
      - ruby/rubocop-check
