default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: gateway_development

test:
  <<: *default
  database: gateway_test

production:
  <<: *default
