---
:max_retries: 25
:concurrency: 1
production:
  :concurrency: 3
:queues:
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge
  - action_mailbox_routing
  - action_mailbox_incineration
